-- CreateTable
CREATE TABLE "public"."ranking_pages" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "content" TEXT,
    "metaTitle" TEXT,
    "metaDescription" TEXT,
    "metaKeywords" TEXT[],
    "countryId" TEXT,
    "cityId" TEXT,
    "subAreaId" TEXT,
    "categoryId" TEXT,
    "subCategoryId" TEXT,
    "limit" INTEGER NOT NULL DEFAULT 10,
    "sortBy" TEXT NOT NULL DEFAULT 'rating',
    "customCompanies" TEXT[],
    "excludedCompanies" TEXT[],
    "viewsCount" INTEGER NOT NULL DEFAULT 0,
    "clicksCount" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "publishedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ranking_pages_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ranking_pages_slug_key" ON "public"."ranking_pages"("slug");

-- CreateIndex
CREATE INDEX "ranking_pages_slug_idx" ON "public"."ranking_pages"("slug");

-- CreateIndex
CREATE INDEX "ranking_pages_isActive_idx" ON "public"."ranking_pages"("isActive");

-- CreateIndex
CREATE INDEX "ranking_pages_countryId_idx" ON "public"."ranking_pages"("countryId");

-- CreateIndex
CREATE INDEX "ranking_pages_cityId_idx" ON "public"."ranking_pages"("cityId");

-- CreateIndex
CREATE INDEX "ranking_pages_categoryId_idx" ON "public"."ranking_pages"("categoryId");

-- CreateIndex
CREATE INDEX "ranking_pages_subCategoryId_idx" ON "public"."ranking_pages"("subCategoryId");

-- CreateIndex
CREATE INDEX "ranking_pages_isAutoGenerated_idx" ON "public"."ranking_pages"("isAutoGenerated");

-- CreateIndex
CREATE INDEX "ranking_pages_publishedAt_idx" ON "public"."ranking_pages"("publishedAt");

-- AddForeignKey
ALTER TABLE "public"."ranking_pages" ADD CONSTRAINT "ranking_pages_countryId_fkey" FOREIGN KEY ("countryId") REFERENCES "public"."countries"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ranking_pages" ADD CONSTRAINT "ranking_pages_cityId_fkey" FOREIGN KEY ("cityId") REFERENCES "public"."cities"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ranking_pages" ADD CONSTRAINT "ranking_pages_subAreaId_fkey" FOREIGN KEY ("subAreaId") REFERENCES "public"."sub_areas"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ranking_pages" ADD CONSTRAINT "ranking_pages_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "public"."categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ranking_pages" ADD CONSTRAINT "ranking_pages_subCategoryId_fkey" FOREIGN KEY ("subCategoryId") REFERENCES "public"."sub_categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;
