/**
 * ملف التوجيهات القديمة (Legacy Redirects)
 *
 * يحتوي على جميع روابط التوجيه من الدومين القديم murabaat.com إلى الدومين الجديد twsia.com
 * تم إنشاؤه تلقائياً من ملف redirect.csv
 *
 * نوع التوجيه: 301 (Permanent Redirect)
 */

const legacyRedirects = [
  {
    source: "/mrkz-alaa-al-dyn-al-tkhssy-al-tby",
    destination: "/aladdin-specialized-medical-center",
  },
  { source: "/al-byrqdar-ltjarh-al-syarat", destination: "/al-byrqdar-cars" },
  { source: "/baik-bash-hotel-fndq-byk-bash", destination: "/baik-bash-hotel" },
  {
    source: "/fndq-qsr-al-shhbndr-al-athry",
    destination: "/shahbandar-palace-hotel",
  },
  {
    source: "/mshfa-al-andls-al-jamay",
    destination: "/al-andalus-university-hospital",
  },
  {
    source: "/mjwhrat-nbyl-_-nabils-jewelery",
    destination: "/jewelry-nbyl-_-nabils-jewelery",
  },
  {
    source: "/shrkh-al-mndyl-llitarat-al-aal-myh",
    destination: "/al-mandeel-tires-company",
  },
  {
    source: "/country/jo/city/amman/sub-area/sweifieh",
    destination: "/country/jo/city/amman/sub-area/sweifieh",
  },
  {
    source: "/mktb-khlyl-aly-ltjarh-al-syarat",
    destination: "/khalil-ali-cars-office",
  },
  { source: "/rwdh-sayd-al-khash", destination: "/saeed-private-kindergarten" },
  { source: "/rwdh-st-al-wfaa", destination: "/set-al-wafa-kindergarten" },
  { source: "/qhwh-al-qshlh", destination: "/al-qashla-cafe" },
  {
    source: "/mktb-yasr-al-shamy",
    destination: "/yasser-al-shami-cars-office",
  },
  {
    source: "/shrkh-al-rstm-al-tjaryh",
    destination: "/al-rustom-trading-company",
  },
  { source: "/mais-private-school", destination: "/mais-private-school" },
  { source: "/najeb-cars", destination: "/najeb-cars" },
  {
    source: "/country/sy/category/beauty-centers",
    destination: "/country/sy/category/beauty-centers",
  },
  {
    source: "/mdrsh-al-hkmh-al-khash-yal-swydaa",
    destination: "/al-hikma-private-school",
  },
  { source: "/companies", destination: "/companies" },
  {
    source: "/mjmwah-al-qwafl-llshhn-al-dwly",
    destination: "/al-qwafl-for-international-shipping",
  },
  {
    source: "/jamah-al-sham-al-khash-aspu-fra-al-ladhqyh",
    destination: "/al-sham-private-university-latakia",
  },
  {
    source: "/mdars-sma-hwran-al-khash",
    destination: "/samaa-horan-private-school",
  },
  {
    source: "/hotel-dedeman-royal-club",
    destination: "/hotel-dedeman-royal-club",
  },
  { source: "/mjwhrat-al-krym", destination: "/jewelry-al-krym" },
  {
    source: "/rwdh-al-frh-al-khash",
    destination: "/al-farah-private-kindergarten",
  },
  { source: "/afnan-al-marfh", destination: "/afnan-al-marfh" },
  { source: "/rwdh-sham-al-syah", destination: "/sham-al-sayyah-kindergarten" },
  {
    source: "/rwdh-al-nsha-al-jdyd",
    destination: "/new-generation-kindergarten",
  },
  { source: "/syty-kar", destination: "/city-car" },
  { source: "/rwdh-byty-al-dafe", destination: "/my-warm-home-kindergarten" },
  {
    source: "/shrkh-samr-mhrm-lqta-al-syarat",
    destination: "/samer-moharem-company",
  },
  { source: "/rwdh-lma-al-sham", destination: "/lama-al-sham-kindergarten" },
  {
    source: "/hanifa-alomar-jewelry-syria",
    destination: "/hanifa-alomar-jewellery-syria",
  },
  {
    source: "/mshfa-al-tyar-al-jrahy",
    destination: "/al-tayyar-surgical-hospital",
  },
  {
    source: "/al-tynawy-ltajyr-al-syarat",
    destination: "/altayenawi-car-rental",
  },
  { source: "/mktb-blywn-ltjarh-al-syarat", destination: "/blion-cars-office" },
  { source: "/mdrsh-al-adhm-al-khash", destination: "/al-adhm-private-school" },
  {
    source: "/rwdh-al-shraa-al-khash",
    destination: "/al-shiraa-private-kindergarten",
  },
  { source: "/mjwhrat-al-qwsrh", destination: "/jewelry-al-qwsrh" },
  { source: "/tal-ysman-al-amyn", destination: "/talisman-hotel" },
  {
    source: "/nswh-yasyn-llstaer-wal-mfrwshat",
    destination: "/nasouh-yaseen-curtains-furniture",
  },
  {
    source: "/mard-ryf-idlb-al-jnwby-zkrya-slyman",
    destination: "/zakaria-suleiman-car-showroom",
  },
  {
    source: "/mktb-swryana-ltjarh-al-syarat",
    destination: "/souryana-cars-office",
  },
  {
    source: "/shrkh-hlb-astyrad-qta-ghyar-syarat-swzwky-syny",
    destination: "/aleppo-car-parts-company",
  },
  {
    source: "/country/eg/city/cairo/category/transportation-shipping-companies",
    destination:
      "/country/eg/city/cairo/category/transportation-shipping-companies",
  },
  { source: "/mard-fyana-lsyarat", destination: "/fayana-cars-showroom" },
  {
    source: "/country/sy/city/idlib/category/Taxi-offices",
    destination: "/country/sy/city/idlib/category/Taxi-offices",
  },
  {
    source: "/mdrsh-w-rwdh-abda-al-khash",
    destination: "/abdaa-private-school-kindergarten",
  },
  {
    source: "/bnwt-lmaayrh-al-dhhb-wal-fdh",
    destination: "/banout-gold-silver",
  },
  {
    source: "/mrkz-al-qmh-llkmbywtr-wal-atsal-at",
    destination: "/al-qimma-center",
  },
  { source: "/mjwhrat-lyan", destination: "/jewelry-lyan" },
  { source: "/silver-lazord-midan", destination: "/lazord-silver-midan" },
  {
    source: "/shrkh-aal-m-al-kwry-al-tjaryh",
    destination: "/korean-world-trading-company",
  },
  {
    source: "/salem-dayan-accessories",
    destination: "/salem-dayan-accessories",
  },
  { source: "/category/Taxi-offices", destination: "/category/Taxi-offices" },
  {
    source: "/country/sy/city/damascus/sub-area/medhat-basha-souq",
    destination: "/country/sy/city/damascus/sub-area/medhat-basha-souq",
  },
  {
    source: "/mktb-al-mstqbl-llshhn-al-dwly",
    destination: "/al-mustaqbal-international-shipping",
  },
  { source: "/mstshfa-faawr", destination: "/faour-hospital" },
  // تم حذف توجيه الصفحة الرئيسية "/" لتجنب حلقة التوجيه
  { source: "/country/sy", destination: "/country/sy" },
  {
    source: "/shrkh-mhmd-bsam-draw",
    destination: "/mohammad-bassam-daraw-company",
  },
  {
    source: "/mfrwshat-abw-shhadh-wawladh",
    destination: "/abu-shahadeh-sons-furniture",
  },
  { source: "/aal-m-al-staer", destination: "/curtains-world" },
  {
    source: "/category/trade-and-retail",
    destination: "/category/trade-and-retail",
  },
  { source: "/sws-school", destination: "/sws-school" },
  {
    source: "/mard-al-brkh-ltjarh-al-syarat",
    destination: "/al-baraka-car-showroom",
  },
  { source: "/mfrwshat-al-natwr", destination: "/al-natour-furniture" },
  {
    source: "/shrkh-jrks-wdhh-al-tjaryh",
    destination: "/jerks-dhha-trading-company",
  },
  {
    source: "/al-jamah-al-dwlyh-llalwm-wal-tknwlwjya-iust",
    destination: "/international-university-science-technology",
  },
  { source: "/mstshfa-al-twfyq", destination: "/al-tawfiq-hospital" },
  { source: "/mrkz-ayfa", destination: "/eva-center" },
  {
    source: "/drmajd-mardn-dental-clinic",
    destination: "/dr-majd-mardn-dental-clinic",
  },
  { source: "/sulla-luna", destination: "/sulla-luna" },
  {
    source: "/mard-al-wlyd-ltjarh-al-syarat",
    destination: "/al-waleed-car-showroom",
  },
  {
    source: "/thanwyh-al-tfwq-al-khash",
    destination: "/al-tafawuq-private-highschool",
  },
  {
    source: "/mard-fady-hsn-llsyarat",
    destination: "/fadi-hassan-car-showroom",
  },
  {
    source: "/rwdh-braam-al-aslam-al-nmwdhjyh",
    destination: "/baraem-islam-kindergarten",
  },
  { source: "/rwdh-wndrland", destination: "/wonderland-kindergarten" },
  {
    source: "/bytza-al-ryf-al-iytal-yh",
    destination: "/italian-village-pizza",
  },
  { source: "/mshfa-al-kndy", destination: "/al-kindi-hospital" },
  { source: "/rwdh-al-bnfsj", destination: "/al-banafsaj-kindergarten" },
  { source: "/riviera-hotel", destination: "/riviera-hotel" },
  {
    source: "/jwd-llatarat-wmstlzmat-al-syarat",
    destination: "/joud-car-tires",
  },
  {
    source: "/jwd-llatarat-wmstlzmat-al-syarat",
    destination: "/jwd-llatarat-wmstlzmat-al-syarat",
  },
  { source: "/mshfa-al-shrq", destination: "/al-sharq-hospital" },
  {
    source: "/rwdh-mnarh-dmshq-al-khash",
    destination: "/manarat-damascus-private-kindergarten",
  },
  { source: "/fndq-barwn", destination: "/baron-hotel" },
  { source: "/fndq-bab-twma-al-athry", destination: "/bab-touma-hotel" },
  { source: "/ashq-shrqy", destination: "/eshq-sharqi" },
  {
    source: "/smart-shybyngh-lkhdmat-al-shhn-al-dwly-w-al-tkhlys",
    destination: "/smart-shybyngh-lkhdmat-al-shhn-al-dwly-w-al-tkhlys",
  },
  {
    source: "/mshfa-al-ashrfyh-al-tkhssy",
    destination: "/al-ashrafieh-specialty-hospital",
  },
  {
    source: "/country/sy/city/damascus/sub-area/alksaa",
    destination: "/country/sy/city/damascus/sub-area/alksaa",
  },
  {
    source: "/mstshfa-al-slam-al-tkhssy-bdmshq",
    destination: "/al-salam-specialty-hospital-damascus",
  },
  { source: "/mjwhrat-al-mslmany", destination: "/jewelry-al-mslmany" },
  { source: "/mrzh-llsyaghh", destination: "/mrzh-llsyaghh" },
  {
    source: "/shrkh-al-azy-lshhn-wtkhlys-al-jmrky",
    destination: "/company-al-azy-lshhn-wtkhlys-al-jmrky",
  },
  {
    source: "/al-jamah-al-swryh-al-khash-spu",
    destination: "/al-jamah-al-swryh-al-khash-spu",
  },
  {
    source: "/mshfa-al-ayn-wal-adhn-al-tkhssy",
    destination: "/eye-ear-specialty-hospital",
  },
  {
    source: "/mydtrans-llmlahh-w-al-khdmat",
    destination: "/mydtrans-llmlahh-w-al-khdmat",
  },
  {
    source: "/rwdh-shms-al-ghd-al-khash",
    destination: "/kindergarten-shms-al-ghd-al-khash",
  },
  { source: "/country/sy/city/idlib", destination: "/country/sy/city/idlib" },
  {
    source: "/mdars-bnah-al-ajyal-al-khash",
    destination: "/bonat-al-ajyal-private-school",
  },
  { source: "/mshfa-al-mna", destination: "/al-muna-hospital" },
  {
    source: "/mdars-al-marfh-al-khash",
    destination: "/al-maarifah-private-school",
  },
  {
    source: "/mdrsh-al-krml-al-khash",
    destination: "/al-karamel-private-school",
  },
  {
    source: "/mdrsh-al-ghsanyh-al-arthwdhksyh-al-khash",
    destination: "/al-ghassaniyah-private-school",
  },
  { source: "/alchaer-jewellery", destination: "/alchaer-jewellery" },
  { source: "/hotel-al-jawaher", destination: "/hotel-al-jawaher" },
  { source: "/hotel-al-faisal", destination: "/hotel-al-faisal" },
  {
    source: "/country/sy/city/aleppo/sub-area/afrin/category/hospitals-clinics",
    destination:
      "/country/sy/city/aleppo/sub-area/afrin/category/hospitals-clinics",
  },
  {
    source: "/mdrsh-al-alm-al-hdyth-al-khash",
    destination: "/modern-science-private-school",
  },
  {
    source: "/mdrsh-al-mnhl-al-khash",
    destination: "/al-manhal-private-school",
  },
  {
    source: "/mdrsh-dwhh-al-wrwd-al-khash",
    destination: "/dawhat-al-warod-private-school",
  },
  { source: "/fndq-byt-al-wal-y", destination: "/beit-al-wali-hotel" },
  { source: "/al-brj", destination: "/al-brj" },
  { source: "/fndq-al-qsr", destination: "/al-qasr-hotel" },
  {
    source: "/mstshfa-al-dyaa-al-jrahy",
    destination: "/al-diaa-surgical-hospital",
  },
  {
    source: "/mdrsh-al-amtyaz-al-khash-alemtiaz-private-school",
    destination: "/al-imtiaz-private-school",
  },
  { source: "/mshfa-al-hryry", destination: "/al-hariri-hospital" },
  {
    source: "/category/educational-centers",
    destination: "/category/educational-centers",
  },
  { source: "/fndq-hms-al-kbyr", destination: "/homs-al-kbyr-hotel" },
  { source: "/sbah-wmsaa", destination: "/sbah-wmsaa" },
  { source: "/mdrsh-al-andls", destination: "/al-andalus-school" },
  { source: "/mdrsh-al-abaa-al-arby", destination: "/al-abaa-arabi-school" },
  { source: "/mshfa-al-sham-al-tby", destination: "/al-sham-medical-hospital" },
  { source: "/mjwhrat-al-aly", destination: "/jewelry-al-aly" },
  { source: "/deluca", destination: "/deluca" },
  {
    source: "/yasmeen-dalep-boutique-hotel",
    destination: "/yasmeen-dalep-boutique-hotel",
  },
  {
    source: "/mstshfa-al-dktwr-mhmd-dbyt",
    destination: "/dr-mohamad-dbyt-hospital",
  },
  {
    source: "/country/sy/city/aleppo/sub-area/azaz",
    destination: "/mstshfa-al-dktwr-mhmd-dbyt",
  },
  {
    source: "/country/sy/city/damascus/sub-area/aladawi",
    destination: "/country/sy/city/aleppo/sub-area/azaz",
  },
  {
    source: "/mstshfa-al-twlyd-al-askry",
    destination: "/military-maternity-hospital",
  },
  {
    source: "/mdrsh-al-mnarh-al-khash",
    destination: "/al-manarah-private-school",
  },
  {
    source: "/the-national-evangelical-school",
    destination: "/the-national-evangelical-school",
  },
  {
    source: "/mdars-al-mkhtar-al-nmwdhjyh-al-khash",
    destination: "/al-mukhtar-model-private-school",
  },
  { source: "/mntja-al-shate-al-azrq", destination: "/mntja-al-shate-al-azrq" },
  { source: "/al-hashmyh-al-khash", destination: "/al-hashmyh-al-khash" },
  { source: "/sndwysh-kyfwrk", destination: "/sndwysh-kyfwrk" },
  { source: "/tl-bany", destination: "/tl-bany" },
  {
    source: "/mdrsh-al-ttbyqat-al-nmwdhjyh-al-khash",
    destination: "/model-applications-private-school",
  },
  { source: "/mdrsh-al-ala-al-khash", destination: "/al-oula-private-school" },
  {
    source: "/mdrsh-jnh-al-asafyr-al-khash",
    destination: "/jannah-al-asafir-private-school",
  },
  {
    source: "/jamah-al-shhbaa-al-khash-al-mbna-al-jdyd",
    destination: "/jamah-al-shhbaa-al-khash-al-mbna-al-jdyd",
  },
  {
    source: "/alkair-palace-hotel-and-restaurant",
    destination: "/alkair-palace-hotel-and-restaurant",
  },
  { source: "/fndq-al-zhran", destination: "/al-zahran-hotel" },
  {
    source: "/mdrsh-al-rdwan-al-khash",
    destination: "/al-ridwan-private-school",
  },
  {
    source: "/mdrsh-ywhna-al-dmshqy-al-khash",
    destination: "/yuhanna-dimashqi-private-school",
  },
  { source: "/mjwhrat-anwar-al-mdynh", destination: "/jewelry-anwar-al-mdynh" },
  { source: "/search", destination: "/search" },
  { source: "/zekreat-jewellery", destination: "/zekreat-jewellery" },
  { source: "/mdrsh-al-mdynh-al-sghyrh", destination: "/little-city-school" },
  { source: "/lali-jewels", destination: "/lali-jewels" },
  { source: "/mstshfa-al-aasy-al-jdyd", destination: "/new-assi-hospital" },
  {
    source: "/jamah-al-athad-al-khash",
    destination: "/jamah-al-athad-al-khash",
  },
  { source: "/afnan-charming-hotel", destination: "/afnan-charming-hotel" },
  { source: "/bkry-abw-shar", destination: "/bkry-abw-shar" },
  {
    source: "/al-mdrsh-al-ywsfyh-llbnat",
    destination: "/yousifiya-girls-school",
  },
  {
    source: "/chanel-jewelry-mjwhrat-shanyl",
    destination: "/chanel-jewelry-mjwhrat-shanyl",
  },
  { source: "/mdrsh-al-aml-al-khash", destination: "/al-amal-private-school" },
  {
    source: "/thanwyh-al-awdh-al-khash",
    destination: "/highschool-al-awdh-al-khash",
  },
  { source: "/awksjyn-o2", destination: "/awksjyn-o2" },
  {
    source: "/rwdh-al-yasmyn-al-khash",
    destination: "/kindergarten-al-yasmyn-al-khash",
  },
  { source: "/mjwhrat-al-adhm", destination: "/jewelry-al-adhm" },
  { source: "/fndq-aal-bal", destination: "/aal-bal-hotel" },
  { source: "/hdanh-al-nwr-al-khash", destination: "/hdanh-al-nwr-al-khash" },
  { source: "/lyana-jewellery", destination: "/lyana-jewellery" },
  { source: "/mard-rajw", destination: "/mard-rajw" },
  {
    source: "/mswghat-abd-al-rhmn-hlywy",
    destination: "/mswghat-abd-al-rhmn-hlywy",
  },
  {
    source: "/category/trade-and-retail",
    destination: "/category/trade-and-retail",
  },
  { source: "/hanania-hotel", destination: "/hanania-hotel" },
  {
    source: "/thanwyh-dmshq-al-wtnyh",
    destination: "/highschool-dmshq-al-wtnyh",
  },
  { source: "/mdrsh-nwr-al-fjr", destination: "/nour-al-fajr-school" },
  { source: "/mjwhrat-asamh", destination: "/jewelry-asamh" },
  { source: "/mwlya", destination: "/mwlya" },
  { source: "/mdrsh-al-klmh", destination: "/al-kalima-school" },
  {
    source: "/mshfa-al-asad-al-jrahy",
    destination: "/al-assaad-surgical-hospital",
  },
  {
    source: "/country/sy/city/homs/category/hospitals-clinics",
    destination: "/country/sy/city/homs/category/hospitals-clinics",
  },
  {
    source:
      "/country/sy/city/latakia/category/transportation-shipping-companies",
    destination:
      "/country/sy/city/latakia/category/transportation-shipping-companies",
  },
  { source: "/rwdh-al-ans", destination: "/kindergarten-al-ans" },
  {
    source: "/shrkh-al-rafdyn-llshhn-w-al-nql",
    destination: "/company-al-rafdyn-llshhn-w-al-nql",
  },
  { source: "/fndq-lwrws", destination: "/laurus-hotel" },
  { source: "/country/sy/city/tartus", destination: "/country/sy/city/tartus" },
  { source: "/shrkh-fnc", destination: "/company-fnc" },
  {
    source: "/al-mstshfa-al-tby-al-jrahy",
    destination: "/medical-surgical-hospital",
  },
  { source: "/izes-hotel", destination: "/izes-hotel" },
  {
    source: "/country/sy/city/homs/category/hotels-resorts",
    destination: "/country/sy/city/homs/category/hotels-resorts",
  },
  { source: "/fndq-awrba", destination: "/europa-hotel" },
  { source: "/azizieh-hospital", destination: "/azizieh-hospital" },
  { source: "/fndq-antradws", destination: "/antradus-hotel" },
  { source: "/mjwhrat-al-jndly", destination: "/jewelry-al-jndly" },
  { source: "/fndq-armtaj", destination: "/armtage-hotel" },
  {
    source: "/mshfa-al-wtn-al-khas",
    destination: "/al-watan-private-hospital",
  },
  {
    source: "/mjwhrat-al-rkn-al-dhhby",
    destination: "/jewelry-al-rkn-al-dhhby",
  },
  { source: "/life-line-clinics", destination: "/life-line-clinics" },
  {
    source: "/rwdh-asafyr-al-jnh",
    destination: "/kindergarten-asafyr-al-jnh",
  },
  {
    source: "/country/lb/category/commercial-shops",
    destination: "/country/lb/category/commercial-shops",
  },
  {
    source: "/mshfa-al-tb-al-arby-al-jrahy",
    destination: "/arabic-medicine-surgical-hospital",
  },
  {
    source: "/mdrsh-bny-tghlb-al-thanyh-al-khash",
    destination: "/bani-taghleb-2-private-school",
  },
  {
    source: "/mdrsh-sydh-al-frh-al-khash",
    destination: "/sayidat-al-farah-private-school",
  },
  { source: "/royal-suites-hotel", destination: "/royal-suites-hotel" },
  { source: "/agenor-hotel", destination: "/agenor-hotel" },
  {
    source: "/mdrsh-al-mnyr-al-talymyh-al-khash",
    destination: "/al-moneer-private-school",
  },
  { source: "/tourist-hotel", destination: "/tourist-hotel" },
  {
    source: "/mdrsh-rwdh-al-hyaa-al-khash",
    destination: "/al-hayat-private-school",
  },
  {
    source: "/mdrsh-al-thanwyh-al-mhsnyh-llbnyn",
    destination: "/al-mohsiniya-school",
  },
  {
    source: "/mnzwmh-bshaer-al-ayman-mdrsh-al-rghd-al-khash",
    destination: "/al-raghad-private-school",
  },
  { source: "/boustan-hotel", destination: "/boustan-hotel" },
  {
    source: "/al-jamah-al-dwlyh-llmaal-jh-al-snyh-al-shamlh-wal-mjanbh",
    destination: "/al-jamah-al-dwlyh-llmaal-jh-al-snyh-al-shamlh-wal-mjanbh",
  },
  { source: "/dndnh-kafyh", destination: "/dndnh-kafyh" },
  { source: "/mshfa-al-razy-al-jdyd", destination: "/al-razy-new-hospital" },
  {
    source: "/almashreq-hospital-mstshfa-al-mshrq",
    destination: "/almashreq-hospital",
  },
  {
    source: "/mdrsh-jyl-al-ghd-al-khash",
    destination: "/jil-al-ghad-private-school",
  },
  { source: "/al-mdrsh-al-amrykyh", destination: "/american-school" },
  {
    source: "/mshfa-al-astshary-al-hdyth",
    destination: "/modern-consulting-hospital",
  },
  {
    source: "/mshfa-dar-al-aywn-wal-tjmyl",
    destination: "/dar-aloyoun-cosmetic-hospital",
  },
  {
    source: "/mdrsh-shms-al-maarf-al-khash",
    destination: "/shams-al-maaref-private-school",
  },
  { source: "/golden-beach-hotel", destination: "/golden-beach-hotel" },
  {
    source: "/mstshfa-bdya-hmwdh-al-jrahy",
    destination: "/badea-hamoudeh-surgical-hospital",
  },
  { source: "/jdayde-hotel", destination: "/jdayde-hotel" },
  { source: "/companies", destination: "/companies" },
  {
    source: "/felicity-solar-service-maintenance-center",
    destination: "/felicity-solar-service-maintenance-center",
  },
  { source: "/mjwhrat-dhkryat", destination: "/jewelry-dhkryat" },
  { source: "/fndq-byt-al-mmlwkh", destination: "/fbeit-al-mamloukeh-hotel" },
  {
    source: "/mshfa-al-raayh-al-khash",
    destination: "/al-rayah-private-hospital",
  },
  { source: "/rwdh-al-rshyd", destination: "/kindergarten-al-rshyd" },
  {
    source: "/mdrsh-al-aasyh-al-khash",
    destination: "/al-asiya-private-school",
  },
  { source: "/fndq-brj-al-shahyn", destination: "/burj-al-shahyn-hotel" },
  {
    source: "/mshfa-al-ahram-al-tkhssy",
    destination: "/al-ahram-specialty-hospital",
  },
  { source: "/mdrsh-al-frh-al-khash", destination: "/al-farah-private-school" },
  { source: "/fallouh-house", destination: "/fallouh-house" },
  {
    source: "/mjwhrat-al-ghrywaty-lldhhb",
    destination: "/jewelry-al-ghrywaty-lldhhb",
  },
  {
    source: "/thanwyh-mahd-al-njah-al-khash-llbnat",
    destination: "/highschool-mahd-al-njah-al-khash-llbnat",
  },
  {
    source: "/sham-lltaqh-al-solar-wal-btaryat",
    destination: "/sham-lltaqh-al-shmsyh-wal-btaryat",
  },
  { source: "/rwdh-al-mshaal", destination: "/kindergarten-al-mshaal" },
  { source: "/shrkh-hbh-al-hdythh", destination: "/company-hbh-al-hdythh" },
  { source: "/rwdh-njwm-al-ghd", destination: "/kindergarten-njwm-al-ghd" },
  { source: "/la-capital-damas", destination: "/la-capital-damas" },
  { source: "/mshfa-al-aysa", destination: "/al-ayssa-hospital" },
  { source: "/fndq-qsr-al-shrq", destination: "/qasr-al-sharq-hotel" },
  { source: "/max-power", destination: "/max-power" },
  { source: "/mjwhrat-bsam-tamh", destination: "/jewelry-bsam-tamh" },
  { source: "/royal-gold", destination: "/royal-gold" },
  { source: "/mshfa-al-mdynh", destination: "/al-madina-hospital" },
  { source: "/syf-w-shty", destination: "/syf-w-shty" },
  { source: "/mktbauto-bazar", destination: "/officeauto-bazar" },
  {
    source: "/shrkh-al-hyah-lltkhlys-al-jmrky-wal-nql-al-arby-wal-dwly",
    destination: "/company-al-hyah-lltkhlys-al-jmrky-wal-nql-al-arby-wal-dwly",
  },
  { source: "/byt-rman", destination: "/byt-rman" },
  {
    source: "/mdrsh-al-amal-al-rafdh-al-khash",
    destination: "/alamal-alrafedah-private-school",
  },
  { source: "/fndq-al-dywan", destination: "/al-diwan-hotel" },
  { source: "/beit-zaman-hotel", destination: "/beit-zaman-hotel" },
  {
    source: "/mdars-al-amyn-al-khash",
    destination: "/al-ameen-private-school",
  },
  { source: "/amyh", destination: "/amyh" },
  { source: "/hotel-sultan", destination: "/hotel-sultan" },
  {
    source: "/mstshfa-bshyr-aalajaty-lltwlyd",
    destination: "/bashir-maternity-hospital",
  },
  {
    source: "/country/eg/category/technology",
    destination: "/country/eg/category/technology",
  },
  { source: "/country/eg/city/aljiza", destination: "/country/eg/city/aljiza" },
  { source: "/fndq-amyh", destination: "/omyah-hotel" },
  { source: "/mjwhrat-abyd-w-sman", destination: "/jewelry-abyd-w-sman" },
  {
    source: "/al-mdrsh-al-hdythh-al-khash",
    destination: "/al-hadythh-private-school",
  },
  { source: "/fndq-antyk-khan", destination: "/antique-khan-hotel" },
  {
    source: "/coral-julia-dumna-hotel",
    destination: "/coral-julia-dumna-hotel",
  },
  { source: "/mjwhrat-byt-al-dhhb", destination: "/jewelry-byt-al-dhhb" },
  { source: "/dar-halabia-hotel", destination: "/dar-halabia-hotel" },
  { source: "/rubino-jewellery", destination: "/rubino-jewellery" },
  { source: "/mjwhrat-jbwly", destination: "/jewelry-jbwly" },
  {
    source: "/mdrsh-al-aml-al-khash-1",
    destination: "/al-amal-private-school-1",
  },
  { source: "/maher-yazeji-jewellery", destination: "/maher-yazeji-jewellery" },
  { source: "/mdrsh-al-awj-al-khash", destination: "/al-awj-private-school" },
  { source: "/mdrsh-iylaf-al-khash", destination: "/ilaf-private-school" },
  { source: "/mjma-al-sham-al-tby", destination: "/mjma-al-sham-al-tby" },
  {
    source: "/h-house-hotel-fndq-byt-al-jwd-wal-krm",
    destination: "/beit-al-joud-wal-karam-hotel",
  },
  {
    source: "/mstshfa-al-amyn-al-tkhssy",
    destination: "/al-ameen-specialty-hospital",
  },
  { source: "/mjwhrat-al-zyn", destination: "/jewelry-al-zyn" },
  { source: "/fndq-aylya-al-syahy", destination: "/aylya-touristic-hotel" },
  {
    source: "/mshfa-al-rwdh-al-jrahy",
    destination: "/al-rawda-surgical-hospital",
  },
  { source: "/fndq-inana", destination: "/inana-hotel" },
  {
    source: "/hlb-al-jdydh-abn-hyan-al-khash",
    destination: "/hlb-al-jdydh-abn-hyan-al-khash",
  },
  { source: "/services", destination: "/services" },
  {
    source: "/country/sy/city/damascus/sub-area/bab-touma",
    destination: "/country/sy/city/damascus/sub-area/bab-touma",
  },
  {
    source: "/ard-al-dhhb-golden-land",
    destination: "/ard-al-dhhb-golden-land",
  },
  { source: "/fndq-zyn-blas", destination: "/zain-plase-hotel" },
  { source: "/mshfa-al-shfaa", destination: "/al-shifa-hospital" },
  { source: "/btwq", destination: "/btwq" },
  {
    source: "/country/sy/category/energy-companies",
    destination: "/country/sy/category/energy-companies",
  },
  {
    source: "/mdrsh-al-msawdyh-al-khash",
    destination: "/masoudiya-private-school",
  },
  { source: "/mshfa-al-jsry", destination: "/al-jasry-hospital" },
  { source: "/rwdh-al-njwm", destination: "/kindergarten-al-njwm" },
  {
    source: "/mjwhrat-abnaa-nwr-al-dyn",
    destination: "/jewelry-abnaa-nwr-al-dyn",
  },
  { source: "/kemareah-hotel", destination: "/kemareah-hotel" },
  {
    source: "/mdrsh-al-mawnh-al-khash-llinath",
    destination: "/al-mawneh-girls-private-school",
  },
  {
    source: "/mswghat-mswghat-ahmd-sbhy-hlywy",
    destination: "/mswghat-mswghat-ahmd-sbhy-hlywy",
  },
  { source: "/al-shahd-llmjwhrat", destination: "/al-shahd-llmjwhrat" },
  { source: "/country/eg/city/cairo", destination: "/country/eg/city/cairo" },
  {
    source: "/mhl-mhmd-hsham-al-khdry",
    destination: "/mhl-mhmd-hsham-al-khdry",
  },
  { source: "/rwad-al-mjd-al-khash", destination: "/rwad-al-mjd-al-khash" },
  {
    source: "/rwdh-al-njwm-al-khash",
    destination: "/kindergarten-al-njwm-al-khash",
  },
  {
    source: "/mdrsh-shate-al-atfal-al-khash-shatea-alatfal-school",
    destination: "/shatea-al-atfal-private-school",
  },
  {
    source: "/mshfa-al-sbyl-al-tkhssy-al-jrahy",
    destination: "/al-sabeel-specialty-surgical-hospital",
  },
  { source: "/mjwhrat-al-mash", destination: "/jewelry-al-mash" },
  {
    source: "/mdrsh-mnahl-al-khyrat-al-khash",
    destination: "/manahil-al-khayrat-private-school",
  },
  { source: "/mdrsh-al-khtwh-al-awla", destination: "/first-step-school" },
  { source: "/mdrsh-dwhh-al-rhab", destination: "/dawhat-al-rahab-school" },
  {
    source: "/mdrsh-abjdyh-al-ghryb-al-khash",
    destination: "/abjadiyat-al-gharib-private-school",
  },
  { source: "/jewellery-nakkashian", destination: "/jewellery-nakkashian" },
  {
    source: "/al-mshfa-al-swry-al-frnsy-al-tkhssy",
    destination: "/syrian-french-specialty-hospital",
  },
  { source: "/hanadi-hotel", destination: "/hanadi-hotel" },
  {
    source: "/country/sy/category/financial-institutions/fnancial-companies",
    destination:
      "/country/sy/category/financial-institutions/fnancial-companies",
  },
  {
    source: "/mdars-al-awael-al-nmwdhjyh-al-khash-llbnat",
    destination: "/al-awail-model-girls-private-school",
  },
  {
    source: "/al-saleh-private-school",
    destination: "/al-saleh-private-school",
  },
  {
    source: "/mshfa-al-twlyd-al-khas",
    destination: "/private-maternity-hospital",
  },
  {
    source: "/thanwyh-al-sham-al-nmwdhjyh-al-khash-llbnyn",
    destination: "/highschool-al-sham-al-nmwdhjyh-al-khash-llbnyn",
  },
  {
    source: "/mdrsh-al-jmhwr-al-khash-llinath",
    destination: "/al-jumhour-girls-private-school",
  },
  { source: "/al-mshfa-al-arby-al-jdyd", destination: "/new-arabic-hospital" },
  { source: "/st-paul-boutiqe-hotel", destination: "/st-paul-boutiqe-hotel" },
  {
    source: "/shamo-jewellery-mjwhrat-shamw",
    destination: "/shamo-jewellery-mjwhrat-shamw",
  },
  {
    source: "/cole-prive-al-riaya-mdrsh-al-raayh-al-khash",
    destination: "/al-riaya-private-school",
  },
  {
    source: "/mdrsh-al-sydh-mrym-al-khash",
    destination: "/sayyidah-maryam-private-school",
  },
  {
    source: "/mrkz-al-andls-llalwm-al-syahyh",
    destination: "/mrkz-al-andls-llalwm-al-syahyh",
  },
  {
    source: "/al-mshfa-al-ahly-al-tkhssy",
    destination: "/al-ahly-specialty-hospital",
  },
  {
    source: "/mdrsh-abn-khldwn-al-khash",
    destination: "/ibn-khaldoun-private-school",
  },
  {
    source: "/nwr-lltqnyat-al-khrbaeyh-wal-taqh-al-shmsyh",
    destination: "/nwr-lltqnyat-al-khrbaeyh-wal-taqh-al-shmsyh",
  },
  {
    source: "/country/sy/category/beauty-centers/hair-care-centers",
    destination: "/country/sy/category/beauty-centers/hair-care-centers",
  },
  {
    source: "/mdrsh-al-zhraa-al-khash-al-martyny",
    destination: "/al-zahraa-private-school",
  },
  { source: "/mshfa-al-hyah", destination: "/al-hayat-hospital" },
  { source: "/mirage-palace-hotel", destination: "/mirage-palace-hotel" },
  { source: "/mdrsh-al-qryh-al-sghyrh", destination: "/little-village-school" },
  {
    source: "/al-mshfa-al-swry-al-tkhssy",
    destination: "/syrian-specialty-hospital",
  },
  {
    source: "/al-jamah-al-arbyh-al-khash-llalwm-wal-tknwlwjya",
    destination: "/al-jamah-al-arbyh-al-khash-llalwm-wal-tknwlwjya",
  },
  {
    source: "/shrkh-mwlr-llshhn-al-dwly",
    destination: "/company-mwlr-llshhn-al-dwly",
  },
  { source: "/mjwhrat-hsn", destination: "/jewelry-hsn" },
  {
    source: "/country/sy/category/energy-companies",
    destination: "/country/sy/category/energy-companies",
  },
  { source: "/ambassador-hotel", destination: "/ambassador-hotel" },
  {
    source: "/country/jo/category/educational-centers",
    destination: "/country/jo/category/educational-centers",
  },
  { source: "/mshfa-al-abasyh", destination: "/al-abbasiyah-hospital" },
  {
    source: "/mshfa-al-zaym-al-tkhssy",
    destination: "/al-zaaim-specialty-hospital",
  },
  {
    source: "/aal-m-al-mjwhratyhya-al-rhal",
    destination: "/aal-m-al-mjwhratyhya-al-rhal",
  },
  {
    source: "/country/eg/city/cairo/sub-area/alzamalik",
    destination: "/country/eg/city/cairo/sub-area/alzamalik",
  },
  { source: "/mswghat-hlb", destination: "/mswghat-hlb" },
  {
    source: "/al-jamah-al-arbyh-al-khash-llalwm-wal-tknwlwjya",
    destination: "/al-jamah-al-arbyh-al-khash-llalwm-wal-tknwlwjya",
  },
  {
    source: "/rwdh-nbras-al-marfh",
    destination: "/kindergarten-nbras-al-marfh",
  },
  { source: "/mktb-ylaghw-hlb", destination: "/office-ylaghw-hlb" },
  {
    source: "/mdrsh-dwhh-al-trbyh-al-khash",
    destination: "/dawhat-al-tarbiyah-private-school",
  },
  {
    source: "/mdrsh-jabr-al-ansary-khash",
    destination: "/jabr-al-ansari-private-school",
  },
  {
    source: "/mossh-tryq-al-njah-al-talymh-al-khash",
    destination: "/mossh-tryq-al-njah-al-talymh-al-khash",
  },
  { source: "/mdrsh-arwad-al-khash", destination: "/arwad-private-school" },
  {
    source: "/mdrsh-al-anayh-al-khash",
    destination: "/al-inayah-private-school",
  },
  {
    source: "/mshfa-smart-kyr-al-tkhssy-smart-care-hospital",
    destination: "/smart-care-specialty-hospital",
  },
  {
    source: "/shrkh-al-shhbaa-llshhn",
    destination: "/company-al-shhbaa-llshhn",
  },
  {
    source: "/mdrsh-al-mkhtar-al-nmwdhjyh",
    destination: "/al-mukhtar-model-school",
  },
  {
    source: "/beit-zafran-hotel-de-charme",
    destination: "/beit-zafran-hotel-de-charme",
  },
  { source: "/turquoise-hotel", destination: "/turquoise-hotel" },
  {
    source: "/mdrsh-fjr-al-tfwq-al-khash",
    destination: "/fajr-al-tafoq-private-school",
  },
  { source: "/abw-jwrj", destination: "/abw-jwrj" },
  { source: "/fndq-al-aamr", destination: "/al-aamer-hotel" },
  { source: "/fndq-bsman", destination: "/basman-hotel" },
  {
    source: "/country/eg/city/cairo/sub-area/city-nasr/category/car-companies",
    destination:
      "/country/eg/city/cairo/sub-area/city-nasr/category/car-companies",
  },
  { source: "/fndq-qsr-al-fars", destination: "/qasr-al-fares-hotel" },
  {
    source: "/country/sy/category/hotels-resorts",
    destination: "/country/sy/category/hotels-resorts",
  },
  {
    source: "/country/sy/category/trade-and-retail/Jewelry-Gold-Shops",
    destination: "/country/sy/category/trade-and-retail/Jewelry-Gold-Shops",
  },
  {
    source: "/country/lb/category/energy-companies",
    destination: "/country/lb/category/energy-companies",
  },
  {
    source: "/mdrsh-aafaq-al-sham-al-khashinath",
    destination: "/afaq-al-sham-private-school",
  },
  { source: "/btc-logistic-syria", destination: "/btc-logistic-syria" },
  {
    source: "/country/sy/city/damascus",
    destination: "/country/sy/city/damascus",
  },
  { source: "/rwdh-al-martqla", destination: "/kindergarten-al-martqla" },
  { source: "/mjwhrat-dha", destination: "/jewelry-dha" },
  {
    source: "/country/eg/category/energy-companies",
    destination: "/country/eg/category/energy-companies",
  },
  {
    source: "/mdrsh-al-njah-al-khash",
    destination: "/al-najah-private-school",
  },
  { source: "/al-mshfa-al-swry", destination: "/alsouri-hospital" },
  {
    source: "/category/educational-centers",
    destination: "/category/educational-centers",
  },
  {
    source: "/mshfa-al-nwr-lltwlyd",
    destination: "/al-noor-maternity-hospital",
  },
  { source: "/mshfa-al-rshyd", destination: "/al-rasheed-hospital" },
  { source: "/fndq-al-bhr-bls", destination: "/bahr-plase-hotel" },
  { source: "/mshfa-bysan", destination: "/baysan-hospital" },
  { source: "/fndq-trtws-al-kbyr", destination: "/tartous-grand-hotel" },
  { source: "/mstshfa-al-hkmh", destination: "/hikma-hospital" },
  { source: "/mdrsh-dar-al-slam", destination: "/dar-al-salam-school" },
  { source: "/mshfa-al-asdy", destination: "/al-asady-hospital" },
  { source: "/mjwhrat-wmswghat-kfa", destination: "/jewelry-wmswghat-kfa" },
  {
    source: "/category/educational-centers",
    destination: "/category/educational-centers",
  },
  {
    source: "/country/sy/city/aleppo/sub-area/afrin",
    destination: "/country/sy/city/aleppo/sub-area/afrin",
  },
  { source: "/mdrsh-alya-al-khask", destination: "/aliya-private-school" },
  {
    source: "/category/educational-centers",
    destination: "/category/educational-centers",
  },
  {
    source: "/category/educational-centers",
    destination: "/category/educational-centers",
  },
  { source: "/mjwhrat-brkat", destination: "/jewelry-brkat" },
  {
    source: "/country/eg/category/technology-companies",
    destination: "/country/eg/category/technology-companies",
  },
  { source: "/mdrsh-dar-al-naym", destination: "/dar-al-naeem-school" },
  { source: "/mshfa-al-ahly", destination: "/alahly-hospital" },
  {
    source: "/mshfa-al-shhbaa-al-tkhssy",
    destination: "/al-shahbaa-specialty-hospital",
  },
  { source: "/mstshfa-al-fyhaa", destination: "/fayhaa-hospital" },
  { source: "/mstshfa-al-kndy", destination: "/al-kindi-hospital" },
  { source: "/mshfa-al-shamy", destination: "/al-shami-hospital" },
  {
    source: "/rwdh-w-mdrsh-al-ibdaa-al-khash",
    destination: "/al-ibdaa-private-kindergarten-school",
  },
  { source: "/mshfa-al-mhth", destination: "/al-mahath-hospital" },
  { source: "/mshfa-amyh", destination: "/omyah-hospital" },
  { source: "/brymks-llshhn-al-dwly", destination: "/brymks-llshhn-al-dwly" },
  { source: "/fndq-al-qysr", destination: "/al-qaysar-hotel" },
  {
    source: "/country/eg/city/aljiza/sub-area/alduqi",
    destination: "/country/eg/city/aljiza/sub-area/alduqi",
  },
  { source: "/about", destination: "/about" },
  { source: "/fndq-al-sal-h", destination: "/al-salih-hotel" },
  { source: "/al-mshfa-al-iytal-y", destination: "/italian-hospital" },
  { source: "/mjwhrat-t", destination: "/jewelry-t" },
  {
    source: "/mktb-al-jrjnazy-lajar-al-syarat",
    destination: "/office-al-jrjnazy-lajar-al-syarat",
  },
  {
    source: "/rwdh-al-qswr-al-ahlyh",
    destination: "/kindergarten-al-qswr-al-ahlyh",
  },
  { source: "/auth/signin", destination: "/auth/signin" },
  {
    source: "/mstshfa-hsn-shykh-al-ard-al-tkhssy",
    destination: "/hassan-sheikh-alard-specialty-hospital",
  },
  { source: "/mjwhrat-smyr", destination: "/jewelry-smyr" },
  {
    source: "/rwdh-al-aml-al-khash-1",
    destination: "/kindergarten-al-aml-al-khash-1",
  },
  {
    source: "/category/trade-and-retail",
    destination: "/category/trade-and-retail",
  },
  { source: "/companies", destination: "/companies" },
  {
    source: "/mshfa-al-qdys-lwys-al-frnsy",
    destination: "/saint-louis-french-hospital",
  },
  { source: "/infinity-fitness-gym", destination: "/infinity-fitness-gym" },
  {
    source: "/dar-al-noor-hotel-fndq-dar-al-nwr",
    destination: "/dar-al-noor-hotel",
  },
  { source: "/country/sy/city/aleppo", destination: "/country/sy/city/aleppo" },
  {
    source: "/country/eg/city/cairo/sub-area/city-nasr",
    destination: "/country/eg/city/cairo/sub-area/city-nasr",
  },
  { source: "/category/restaurants", destination: "/category/restaurants" },
  { source: "/category/restaurants", destination: "/category/restaurants" },
  { source: "/lwz-wskr", destination: "/lwz-wskr" },
  { source: "/bshara-jewelry", destination: "/bshara-jewelry" },
  { source: "/mktb-al-arab", destination: "/office-al-arab" },
  {
    source: "/country/eg/city/cairo/sub-area/maadi",
    destination: "/country/eg/city/cairo/sub-area/maadi",
  },
  { source: "/fndq-al-btraa", destination: "/al-batraa-hotel" },
  { source: "/fndq-dywnyzyas", destination: "/dionysias-hotel" },
  {
    source: "/mjwhrat-wmswghat-al-hwrany",
    destination: "/jewelry-wmswghat-al-hwrany",
  },
  {
    source: "/rwdh-snabl-al-khyr",
    destination: "/kindergarten-snabl-al-khyr",
  },
  { source: "/mard-zkrya", destination: "/mard-zkrya" },
  { source: "/mjwhrat-al-wlaa", destination: "/jewelry-al-wlaa" },
  {
    source: "/al-thanwyh-al-ahlyh-al-khash-astfan",
    destination: "/al-thanwyh-al-ahlyh-al-khash-astfan",
  },
  { source: "/lingo-kids", destination: "/lingo-kids" },
  {
    source: "/mdrsh-al-abdaa-al-khash",
    destination: "/al-ebdaa-private-school",
  },
  { source: "/privacy", destination: "/privacy" },
  { source: "/mdrsh-dwhh-al-blabl", destination: "/dawhat-al-balabel-school" },
  { source: "/afamia-hotel-resort", destination: "/afamia-hotel-resort" },
  {
    source: "/country/sy/category/restaurants",
    destination: "/country/sy/category/restaurants",
  },
  {
    source: "/mshfa-al-sydh-al-jrahy",
    destination: "/al-saydeh-surgical-hospital",
  },
  {
    source: "/rwdh-roa-al-mstqbl",
    destination: "/kindergarten-roa-al-mstqbl",
  },
  {
    source: "/jamah-al-sham-al-khash-aspu",
    destination: "/jamah-al-sham-al-khash-aspu",
  },
  {
    source: "/shrkh-alma-lltkhlys-al-jmrky",
    destination: "/company-alma-lltkhlys-al-jmrky",
  },
  { source: "/mjwhrat-al-shryqy", destination: "/jewelry-al-shryqy" },
  {
    source: "/mdrsh-al-tlyah-al-khash-bdmshq",
    destination: "/al-talia-private-school-damascus",
  },
  {
    source: "/country/lb/city/beirut/sub-area/sharie-almasarif",
    destination: "/country/lb/city/beirut/sub-area/sharie-almasarif",
  },
  {
    source: "/country/jo/category/energy-companies",
    destination: "/country/jo/category/energy-companies",
  },
  { source: "/companies", destination: "/companies" },
  { source: "/companies", destination: "/companies" },
  { source: "/companies", destination: "/companies" },
  { source: "/mard-abad-al-rhmn", destination: "/mard-abad-al-rhmn" },
  { source: "/mshfa-al-rhmh", destination: "/al-rahma-hospital" },
  { source: "/pub-shrqy", destination: "/pub-shrqy" },
  {
    source: "/country/sy/category/educational-centers",
    destination: "/country/sy/category/educational-centers",
  },
  {
    source: "/mshfa-tshryn-al-jamay",
    destination: "/tishreen-university-hospital",
  },
  { source: "/mahd-al-rayh", destination: "/mahd-al-rayh" },
  { source: "/fndq-al-hdyqh", destination: "/al-hadiqa-hotel" },
  { source: "/mjwhrat-hydr", destination: "/jewelry-hydr" },
  { source: "/adib-jewelery", destination: "/adib-jewelery" },
  { source: "/mshfa-al-razy", destination: "/al-razy-hospital" },
  { source: "/fndq-tdmr", destination: "/tadmor-hotel" },
  { source: "/fndq-sfyr-hms", destination: "/safir-homs-hotel" },
  { source: "/shrkh-shhn-al-hythm", destination: "/company-shhn-al-hythm" },
  {
    source: "/country/lb/category/technology",
    destination: "/country/lb/category/technology",
  },
  { source: "/krfan-llshhn-al-dwly", destination: "/krfan-llshhn-al-dwly" },
  {
    source: "/rwdh-wmdrsh-al-nwr-al-khash",
    destination: "/al-noor-private-kindergarten-school",
  },
  { source: "/mjwhrat-al-bdwy", destination: "/jewelry-al-bdwy" },
  { source: "/mard-tftnaz", destination: "/mard-tftnaz" },
  { source: "/rwdh-shmws-al-ghd", destination: "/kindergarten-shmws-al-ghd" },
  { source: "/mktb-sraqb", destination: "/office-sraqb" },
  { source: "/braam-aadhar", destination: "/braam-aadhar" },
  { source: "/mktb-banyas", destination: "/office-banyas" },
  { source: "/rwdh-al-kwkh", destination: "/kindergarten-al-kwkh" },
  { source: "/fndq-klasykal", destination: "/classical-hotel" },
  { source: "/mktb-al-sal-h", destination: "/office-al-sal-h" },
  { source: "/shrkh-hwranyh", destination: "/company-hwranyh" },
  { source: "/mjmwah-nhas", destination: "/mjmwah-nhas" },
  { source: "/country/sy/city/aleppo", destination: "/country/sy/city/aleppo" },
  {
    source: "/rwdh-braam-al-ghfran",
    destination: "/kindergarten-braam-al-ghfran",
  },
  { source: "/fndq-abw-al-kmyt", destination: "/abu-al-kamit-hotel" },
  { source: "/mstshfa-al-mwasah", destination: "/al-muwasat-hospital" },
  {
    source: "/al-ywsf-llshhn-al-dwly-fra-hmah",
    destination: "/al-ywsf-llshhn-al-dwly-fra-hmah",
  },
  {
    source: "/rwdh-yasmyn-al-sham",
    destination: "/kindergarten-yasmyn-al-sham",
  },
  { source: "/shrkh-abw-zynw", destination: "/company-abw-zynw" },
  { source: "/mshfa-al-amwry", destination: "/al-amouri-hospital" },
  { source: "/mard-ahmd-rmdan", destination: "/mard-ahmd-rmdan" },
  { source: "/mjwhrat-mswh", destination: "/jewelry-mswh" },
  {
    source: "/shrkh-al-lwlw-llsyarat",
    destination: "/company-al-lwlw-llsyarat",
  },
  { source: "/sindibad-kindergarten", destination: "/sindibad-kindergarten" },
  {
    source: "/country/sy/city/damascus/sub-area/Altal",
    destination: "/country/sy/city/damascus/sub-area/Altal",
  },
  { source: "/country/lb/city/beirut", destination: "/country/lb/city/beirut" },
  {
    source: "/country/sy/category/sports-facilities",
    destination: "/country/sy/category/sports-facilities",
  },
  { source: "/rwdh-al-rwaby", destination: "/kindergarten-al-rwaby" },
  {
    source: "/rwdh-al-snabl-al-fra-al-awl",
    destination: "/kindergarten-al-snabl-al-fra-al-awl",
  },
  { source: "/mard-mrhf-hdad", destination: "/mard-mrhf-hdad" },
  { source: "/rwdh-al-hkmh", destination: "/kindergarten-al-hkmh" },
  { source: "/rwdh-al-nda", destination: "/kindergarten-al-nda" },
  {
    source: "/kassabian-company-shrkh-qsabyan",
    destination: "/kassabian-company-shrkh-qsabyan",
  },
  { source: "/rwdh-dyzny-kydz", destination: "/kindergarten-dyzny-kydz" },
  { source: "/fndq-sarh", destination: "/sarah-hotel" },
  { source: "/mard-al-hbal", destination: "/mard-al-hbal" },
  { source: "/knq-al-syarat", destination: "/knq-al-syarat" },
  {
    source: "/teacher-motors-abw-mmdwh",
    destination: "/teacher-motors-abw-mmdwh",
  },
  { source: "/mshfa-al-mjd", destination: "/al-majd-hospital" },
  {
    source: "/shrkh-abwras-al-tjaryh-llitarat",
    destination: "/company-abwras-al-tjaryh-llitarat",
  },
  { source: "/rwdh-al-wfaa", destination: "/kindergarten-al-wfaa" },
  { source: "/zeitoun-jewelry", destination: "/zeitoun-jewelry" },
  { source: "/braam-al-nwr", destination: "/braam-al-nwr" },
  { source: "/rwdh-frdw", destination: "/kindergarten-frdw" },
  { source: "/shrkh-mllwk-llsyarat", destination: "/company-mllwk-llsyarat" },
  { source: "/rwdh-al-ala", destination: "/kindergarten-al-ala" },
  { source: "/mjwhrat-al-mhbh", destination: "/jewelry-al-mhbh" },
  { source: "/syro-motors", destination: "/syro-motors" },
  { source: "/mktb-abd-al-jwad", destination: "/office-abd-al-jwad" },
  { source: "/rwdh-al-mamwn", destination: "/kindergarten-al-mamwn" },
  { source: "/mshfa-al-slam", destination: "/al-salam-hospital" },
  { source: "/mjwhrat-kmal", destination: "/jewelry-kmal" },
  { source: "/mstshfa-dar-al-shfaa", destination: "/dar-alshifa-hospital" },
  { source: "/al-barwdyh", destination: "/al-barwdyh" },
  { source: "/mjwhrat-asamh-aaram", destination: "/jewelry-asamh-aaram" },
  { source: "/mstshfa-al-shqqy", destination: "/al-sheqaqi-hospital" },
  { source: "/mjwhrat-dhby-wagha", destination: "/jewelry-dhby-wagha" },
  { source: "/shrkh-mwbs", destination: "/company-mwbs" },
  { source: "/add-company", destination: "/add-company" },
  { source: "/mshfa-al-mal-k", destination: "/al-malek-hospital" },
  { source: "/mswghat-jbran", destination: "/mswghat-jbran" },
  { source: "/mdrshetc-al-khash", destination: "/etc-private-school" },
  { source: "/rwdh-dar-al-mrh", destination: "/kindergarten-dar-al-mrh" },
  { source: "/rwdh-shamna", destination: "/kindergarten-shamna" },
  { source: "/rwdh-al-nwr", destination: "/kindergarten-al-nwr" },
  { source: "/rwdh-tshryn", destination: "/kindergarten-tshryn" },
  { source: "/shrkh-kmal-khyr", destination: "/company-kmal-khyr" },
  { source: "/mstshfa-al-shrq", destination: "/al-sharq-hospital" },
  { source: "/shrkh-khdrh-al-tjaryh", destination: "/company-khdrh-al-tjaryh" },
  { source: "/al-wsyt-lltjarh", destination: "/al-wsyt-lltjarh" },
  { source: "/jwdks-llshhn-al-dwly", destination: "/jwdks-llshhn-al-dwly" },
  { source: "/mktb-al-qysr", destination: "/office-al-qysr" },
  { source: "/terms", destination: "/terms" },
  { source: "/mjwhrat-rtyl", destination: "/jewelry-rtyl" },
  { source: "/mjmwah-shmwt", destination: "/mjmwah-shmwt" },
  {
    source: "/rwdh-azhar-al-bnfsj",
    destination: "/kindergarten-azhar-al-bnfsj",
  },
  { source: "/mdrsh-djlh-al-khash", destination: "/dajla-private-school" },
  {
    source: "/shrkh-hany-abdllh-naym",
    destination: "/company-hany-abdllh-naym",
  },
  {
    source: "/rwdh-snabl-al-tfwlh",
    destination: "/kindergarten-snabl-al-tfwlh",
  },
  {
    source: "/rwdh-aafaq-al-tfwlh",
    destination: "/kindergarten-aafaq-al-tfwlh",
  },
  { source: "/rwdh-drwb-al-nwr", destination: "/kindergarten-drwb-al-nwr" },
  {
    source: "/caramel-preschool-rwdh-karamyl",
    destination: "/caramel-preschool-rwdh-karamyl",
  },
  { source: "/dwhh-al-bshyr", destination: "/dwhh-al-bshyr" },
  {
    source: "/rwdh-al-snabl-al-fra-al-thany",
    destination: "/kindergarten-al-snabl-al-fra-al-thany",
  },
  {
    source: "/rwdh-kmal-al-tfwlh",
    destination: "/kindergarten-kmal-al-tfwlh",
  },
  {
    source: "/rwdh-ahlam-al-tfwlh",
    destination: "/kindergarten-ahlam-al-tfwlh",
  },
  { source: "/rwdh-drym-land", destination: "/kindergarten-drym-land" },
  { source: "/rwdh-al-nkhyl", destination: "/kindergarten-al-nkhyl" },
  { source: "/mstshfa-al-hwrany", destination: "/hawrani-hospital" },
  {
    source: "/shrkh-sfwan-dyb-llsyarat",
    destination: "/company-sfwan-dyb-llsyarat",
  },
  { source: "/afamya-al-sham", destination: "/afamya-al-sham" },
  { source: "/aybla-llshhn-al-dwly", destination: "/aybla-llshhn-al-dwly" },
  {
    source: "/country/sy/category/restaurants/cafés",
    destination: "/country/sy/category/restaurants/cafés",
  },
  { source: "/rwdh-nwr-al-ajyal", destination: "/kindergarten-nwr-al-ajyal" },
  { source: "/mdrsh-mary-al-khash", destination: "/mary-private-school" },
  {
    source: "/krfan-llshhn-al-dwly-fra-hmah",
    destination: "/krfan-llshhn-al-dwly-fra-hmah",
  },
  { source: "/rwdh-mama-nbyla", destination: "/kindergarten-mama-nbyla" },
  { source: "/rasal-ltjarh-al-syarat", destination: "/rasal-ltjarh-al-syarat" },
  { source: "/mjwhrat-mtya", destination: "/jewelry-mtya" },
  { source: "/mard-zaza", destination: "/mard-zaza" },
  { source: "/mktb-abw-al-az", destination: "/office-abw-al-az" },
  { source: "/rwdh-dar-al-krm", destination: "/kindergarten-dar-al-krm" },
  {
    source: "/rwdh-mdynh-al-atfal",
    destination: "/kindergarten-mdynh-al-atfal",
  },
  { source: "/mshfa-al-mzrah", destination: "/al-mazraah-hospital" },
  { source: "/abrahym-al-shnth", destination: "/abrahym-al-shnth" },
  { source: "/royal-cars", destination: "/royal-cars" },
  { source: "/mjwhrat-al-rfaay-2", destination: "/jewelry-al-rfaay-2" },
  { source: "/jamah-bshyr-rhyjh", destination: "/jamah-bshyr-rhyjh" },
  { source: "/auto-plus", destination: "/auto-plus" },
  { source: "/mktb-al-skmany", destination: "/office-al-skmany" },
  { source: "/mktb-drwysh-llsyarat", destination: "/office-drwysh-llsyarat" },
  { source: "/alkabbany", destination: "/alkabbany" },
  { source: "/mktb-al-rhwnjy", destination: "/office-al-rhwnjy" },
  { source: "/al-raed-llsyarat", destination: "/al-raed-llsyarat" },
  {
    source: "/rwdh-bshaer-al-iyman",
    destination: "/kindergarten-bshaer-al-iyman",
  },
  { source: "/mlaekh-al-dhhb", destination: "/mlaekh-al-dhhb" },
  { source: "/mjwhrat-al-aamyn", destination: "/jewelry-al-aamyn" },
  { source: "/rwdh-al-zhwr", destination: "/kindergarten-al-zhwr" },
  { source: "/rwdh-al-frqan", destination: "/kindergarten-al-frqan" },
  { source: "/hdanh-bably-land", destination: "/hdanh-bably-land" },
  {
    source: "/qbany-lqta-ghyar-al-syarat",
    destination: "/qbany-lqta-ghyar-al-syarat",
  },
  {
    source: "/mshfa-al-bdr-al-tkhssy",
    destination: "/al-badr-specialty-hospital",
  },
  {
    source: "/mstshfa-d-nasr-shqyr",
    destination: "/dr-nasser-shuqair-hospital",
  },
  {
    source: "/rwdh-snabl-al-nyrb",
    destination: "/kindergarten-snabl-al-nyrb",
  },
  { source: "/shrkh-loy-hmzh", destination: "/company-loy-hmzh" },
  { source: "/rwdh-tlaea-jrmana", destination: "/kindergarten-tlaea-jrmana" },
  {
    source: "/rwdh-ajyal-al-khash",
    destination: "/kindergarten-ajyal-al-khash",
  },
  {
    source: "/rwdh-frdws-al-atfal",
    destination: "/kindergarten-frdws-al-atfal",
  },
  {
    source: "/rwdh-dwhh-al-sghar",
    destination: "/kindergarten-dwhh-al-sghar",
  },
  { source: "/mjwhrat-mlwhy", destination: "/jewelry-mlwhy" },
  { source: "/rwdh-bhr-al-alwm", destination: "/kindergarten-bhr-al-alwm" },
  { source: "/shrkh-al-tas", destination: "/company-al-tas" },
  { source: "/dhl-daraa", destination: "/dhl-daraa" },
  { source: "/mstshfa-al-mtlq", destination: "/al-mutlaq-hospital" },
  {
    source: "/shrkh-mwslly-al-tjaryh",
    destination: "/company-mwslly-al-tjaryh",
  },
  { source: "/syryn-lldhhb", destination: "/syryn-lldhhb" },
  { source: "/mktb-al-shaarllsyarat", destination: "/office-al-shaarllsyarat" },
  { source: "/mswghat-wmjwhrat-krwma", destination: "/mswghat-wmjwhrat-krwma" },
  { source: "/mjwhrat-al-basha", destination: "/jewelry-al-basha" },
  {
    source: "/rwdh-braam-al-aqsa",
    destination: "/kindergarten-braam-al-aqsa",
  },
  { source: "/mshfa-al-zhrawy", destination: "/al-zhrawi-hospital" },
  { source: "/mjwhrat-al-jblawy", destination: "/jewelry-al-jblawy" },
  { source: "/mrtbat-abw-hsn", destination: "/mrtbat-abw-hsn" },
  { source: "/al-byanw-bar", destination: "/al-byanw-bar" },
  {
    source: "/mjwhrat-abrahym-bsath-wawladh",
    destination: "/jewelry-abrahym-bsath-wawladh",
  },
  {
    source: "/mtam-whlwyat-qzyha-bab-twma",
    destination: "/mtam-whlwyat-qzyha-bab-twma",
  },
  {
    source: "/mshfa-al-razy-al-jrahy-al-hdyth",
    destination: "/al-razy-modern-surgical-hospital",
  },
  { source: "/alramli-gifts-lattakia", destination: "/alramli-gifts-lattakia" },
  { source: "/mjwhrat-ywsf", destination: "/jewelry-ywsf" },
  { source: "/al-mshfa-al-mrkzy", destination: "/al-markazi-hospital" },
  {
    source: "/mshfa-al-tabyat-al-jrahy",
    destination: "/al-ttabyatt-surgical-hospital",
  },
  {
    source: "/mshfa-al-twlyd-wal-atfal",
    destination: "/maternity-children-hospital",
  },
  { source: "/al-mstshfa-al-wtny", destination: "/national-hospital" },
  {
    source: "/dr-oussama-haroun-hospital-mshfa-al-dktwr-asamh-harwn",
    destination: "/dr-oussama-haroun-hospital",
  },
  {
    source: "/mshfa-al-bshyr-al-jrahy",
    destination: "/al-basheer-surgical-hospital",
  },
  {
    source: "/country/jo/city/amman/sub-area/alshamaysani",
    destination: "/country/jo/city/amman/sub-area/alshamaysani",
  },
  { source: "/mswghat-bysan", destination: "/mswghat-bysan" },
  { source: "/dwhh-qasywn", destination: "/dwhh-qasywn" },
  {
    source: "/country/jo/city/amman/sub-area/abdoun",
    destination: "/country/jo/city/amman/sub-area/abdoun",
  },
  { source: "/mshfa-al-mhayny", destination: "/al-mhayni-hospital" },
  {
    source: "/country/sy/category/trade-and-retail",
    destination: "/country/sy/category/trade-and-retail",
  },
  { source: "/kafyh-al-hsn", destination: "/kafyh-al-hsn" },
  { source: "/fndq-brj-al-mstqbl", destination: "/burj-al-mustaqbal-hotel" },
  {
    source: "/country/sy/category/software-companies",
    destination: "/country/sy/category/software-companies",
  },
  {
    source: "/category/energy-companies",
    destination: "/category/energy-companies",
  },
  {
    source: "/country/jo/category/software-companies",
    destination: "/country/jo/category/software-companies",
  },
  {
    source: "/category/beauty-centers",
    destination: "/category/beauty-centers",
  },
  {
    source: "/country/sy/category/financial-institutions",
    destination: "/country/sy/category/financial-institutions",
  },
  {
    source: "/country/sy/category/commercial-shops",
    destination: "/country/sy/category/commercial-shops",
  },
  {
    source:
      "/country/sy/city/damascus/sub-area/شارع-القيمرية/category/restaurants",
    destination:
      "/country/sy/city/damascus/sub-area/شارع-القيمرية/category/restaurants",
  },
  { source: "/shrkh-qnws", destination: "/company-qnws" },
  {
    source: "/mazzika-restaurant-lounge",
    destination: "/mazzika-restaurant-lounge",
  },
  {
    source: "/country/jo/category/commercial-shops",
    destination: "/country/jo/category/commercial-shops",
  },
  {
    source: "/mshfa-zahy-azrq-al-askry",
    destination: "/zahi-azraq-military-hospital",
  },
  { source: "/country/jo/city/amman", destination: "/country/jo/city/amman" },
  {
    source: "/mjwhrat-wmswghat-al-tamh",
    destination: "/jewelry-wmswghat-al-tamh",
  },
  {
    source: "/country/jo/category/financial-institutions",
    destination: "/country/jo/category/financial-institutions",
  },
  { source: "/mswghat-frfshh-plus", destination: "/mswghat-frfshh-plus" },
  {
    source: "/country/lb/category/educational-centers",
    destination: "/country/lb/category/educational-centers",
  },
  { source: "/mstshfa-al-haj-sal-h", destination: "/hajj-salah-hospital" },
  {
    source:
      "/country/lb/category/technology-companies/artificial-intelligence-companies",
    destination:
      "/country/lb/category/technology-companies/artificial-intelligence-companies",
  },
  { source: "/tartous", destination: "/tartous" },
  {
    source: "/country/sy/category/restaurants",
    destination: "/country/sy/category/restaurants",
  },
  {
    source: "/category/educational-centers",
    destination: "/category/educational-centers",
  },
  { source: "/mswghat-wmjwhrat-mladh", destination: "/mswghat-wmjwhrat-mladh" },
  {
    source: "/country/sy/city/damascus/sub-area/alhariqa",
    destination: "/country/sy/city/damascus/sub-area/alhariqa",
  },
  {
    source: "/country/sy/city/damascus/sub-area/almalki",
    destination: "/country/sy/city/damascus/sub-area/almalki",
  },
  {
    source: "/country/sy/city/damascus/sub-area/mazzeh",
    destination: "/country/sy/city/damascus/sub-area/mazzeh",
  },
  {
    source: "/country/sy/city/damascus/sub-area/baramkeh",
    destination: "/country/sy/city/damascus/sub-area/baramkeh",
  },
  {
    source: "/country/sy/city/damascus/sub-area/salihiyah",
    destination: "/country/sy/city/damascus/sub-area/salihiyah",
  },
  {
    source: "/country/sy/city/damascus/sub-area/sha'alan",
    destination: "/country/sy/city/damascus/sub-area/sha'alan",
  },
  {
    source: "/country/sy/city/damascus/sub-area/jadet-alshallah",
    destination: "/country/sy/city/damascus/sub-area/jadet-alshallah",
  },
  {
    source: "/country/sy/city/damascus/sub-area/alqaymarya",
    destination: "/country/sy/city/damascus/sub-area/alqaymarya",
  },
  {
    source: "/country/sy/city/damascus/sub-area/jadet-alnahawi",
    destination: "/country/sy/city/damascus/sub-area/jadet-alnahawi",
  },
  {
    source: "/country/sy/city/damascus/sub-area/almidan",
    destination: "/country/sy/city/damascus/sub-area/almidan",
  },
  {
    source: "/country/sy/city/damascus/sub-area/almazra'a",
    destination: "/country/sy/city/damascus/sub-area/almazra'a",
  },
  {
    source: "/country/sy/city/damascus/sub-area/alrawdah",
    destination: "/country/sy/city/damascus/sub-area/alrawdah",
  },
  { source: "/mswghat-wmjwhrat-lylas", destination: "/mswghat-wmjwhrat-lylas" },
  { source: "/g-m-gold", destination: "/g-m-gold" },
  { source: "/mdrsh-rwafd", destination: "/rawafed-school" },
  { source: "/mshfa-al-ashtr", destination: "/al-ashtar-hospital" },
  { source: "/silver-lazord", destination: "/silver-lazord" },
  { source: "/hallak-jewelry", destination: "/hallak-jewelry" },
  { source: "/fndq-al-majd", destination: "/al-majd-hotel" },
  { source: "/mshfa-al-hkmh", destination: "/al-hikmah-hospital" },
  { source: "/mjwhrat-bqlh", destination: "/jewelry-bqlh" },
  { source: "/beit-ramza", destination: "/beit-ramza" },
  { source: "/mhwhrat-sad", destination: "/mhwhrat-sad" },
  { source: "/rm", destination: "/rm" },
  { source: "/mdrsh-dwhh-al-mjd", destination: "/dawhat-al-majd-school" },
  { source: "/mhl-lamas-llmjwhrat", destination: "/mhl-lamas-llmjwhrat" },
  { source: "/mswghat-alaa-jbdwn", destination: "/mswghat-alaa-jbdwn" },
  { source: "/mjwhrat-nmyr-aadl-hydr", destination: "/jewelry-nmyr-aadl-hydr" },
  { source: "/mshfa-dar-al-shfaa", destination: "/dar-alshifa-hospital" },
  {
    source: "/awak-jewelery-mswghat-awk",
    destination: "/awak-jewelery-mswghat-awk",
  },
  { source: "/jwahrjy", destination: "/jwahrjy" },
  { source: "/mjwhrat-twmajan", destination: "/jewelry-twmajan" },
  { source: "/fwr-syzwn", destination: "/fwr-syzwn" },
  { source: "/mjwhrat-al-khyr", destination: "/jewelry-al-khyr" },
  { source: "/fndq-brj-al-frdws", destination: "/burj-al-firdaws-hotel" },
  { source: "/fndq-wmntja-lamyra", destination: "/lamira-resort-hotel" },
  { source: "/sahh-al-syagh", destination: "/sahh-al-syagh" },
  { source: "/mjwhrat-al-syd", destination: "/jewelry-al-syd" },
  { source: "/fndq-arman-arman", destination: "/arman-hotel" },
  { source: "/mjwhrat-al-khyat", destination: "/jewelry-al-khyat" },
  {
    source: "/country/jo/category/technology",
    destination: "/country/jo/category/technology",
  },
  { source: "/al-pasha", destination: "/al-pasha" },
  { source: "/fndq-al-aywan", destination: "/al-aywan-hotel" },
  { source: "/bassil", destination: "/bassil" },
  { source: "/fndq-ghzal", destination: "/ghazal-hotel" },
  { source: "/ibrahem-jewelry", destination: "/ibrahem-jewelry" },
  { source: "/hgroupco", destination: "/hgroupco" },
  { source: "/mjwhrat-ahmd-ghndwr", destination: "/jewelry-ahmd-ghndwr" },
  { source: "/dar-zmrya", destination: "/dar-zmrya" },
  { source: "/mwzayka", destination: "/mwzayka" },
  { source: "/fndq-bwabh-al-shrq", destination: "/bawwabet-al-sharq-hotel" },
  { source: "/beit-wakil", destination: "/beit-wakil" },
  { source: "/fndq-rygha", destination: "/raygha-hotel" },
  {
    source: "/mdrsh-rwdh-al-kwn-al-khash",
    destination: "/rowdat-al-kawn-private-school",
  },
  { source: "/mjwhrat-rnd", destination: "/jewelry-rnd" },
  { source: "/tlaea-al-nwr-al-khash", destination: "/tlaea-al-nwr-al-khash" },
  { source: "/krystal-1", destination: "/krystal-1" },
  { source: "/dar-al-mamlouka", destination: "/dar-al-mamlouka" },
  { source: "/mjwhrat-th", destination: "/jewelry-th" },
  { source: "/fndq-al-sfyr", destination: "/al-safir-hotel" },
  { source: "/mjwhrat-mrhf-bnyan", destination: "/jewelry-mrhf-bnyan" },
  { source: "/mjwhrat-tybh-fra-2", destination: "/jewelry-tybh-fra-2" },
  { source: "/dar-al-kanadil-hotel", destination: "/dar-al-kanadil-hotel" },
  { source: "/touch-store", destination: "/touch-store" },
  {
    source: "/thanwyh-al-saadh-al-khash",
    destination: "/highschool-al-saadh-al-khash",
  },
  { source: "/al-fynyq", destination: "/al-fynyq" },
  { source: "/mdrsh-al-amyrkan", destination: "/american-private-school" },
  {
    source: "/louis-inn-hotel-and-restaurant",
    destination: "/louis-inn-hotel-and-restaurant",
  },
  { source: "/fndq-ramyta", destination: "/ramyta-hotel" },
  { source: "/ghna-mjwhrat-tqlydyh", destination: "/ghna-mjwhrat-tqlydyh" },
  { source: "/wn-mlywn", destination: "/wn-mlywn" },
  { source: "/mjwhrat-sabr", destination: "/jewelry-sabr" },
  { source: "/mswghat-abdllh-jbdwn", destination: "/mswghat-abdllh-jbdwn" },
  { source: "/fndq-shhbaa-hlb", destination: "/shahbaa-aleppo-hotel" },
  { source: "/mstshfa-al-razy", destination: "/al-razi-hospital" },
  {
    source: "/mjwhrat-lyn-leen-jewelleries",
    destination: "/jewelry-lyn-leen-jewelleries",
  },
  { source: "/fndq-kwyn-sntr", destination: "/queen-center-hotel" },
  {
    source: "/mdrsh-mshaal-al-sham-al-khash",
    destination: "/mshaal-al-sham-private-school",
  },
  { source: "/mshfa-al-aryan", destination: "/al-aryan-hospital" },
  { source: "/beit-akbik", destination: "/beit-akbik" },
  {
    source: "/mjwhrat-al-ghdq-alghadaq",
    destination: "/jewelry-al-ghdq-alghadaq",
  },
  { source: "/mjwhrat-yzn-al-tshh", destination: "/jewelry-yzn-al-tshh" },
  { source: "/mjwhrat-mazn-adymh", destination: "/jewelry-mazn-adymh" },
  {
    source: "/mdrsh-al-awael-llbnat-fra-al-akrm",
    destination: "/al-awail-girls-school-akram",
  },
  { source: "/mstshfa-aysa", destination: "/aissa-hospital" },
  { source: "/mjwhrat-tyfany-tiffany", destination: "/jewelry-tyfany-tiffany" },
  { source: "/fndq-dama-rwz", destination: "/dama-rose-hotel" },
  {
    source: "/taifor-fashion-accessories",
    destination: "/taifor-fashion-accessories",
  },
  { source: "/mstshfa-al-rjaa", destination: "/al-rajaa-hospital" },
  { source: "/happy-nights-hotel", destination: "/happy-nights-hotel" },
  { source: "/shama-gaan", destination: "/shama-gaan" },
  { source: "/mshfa-al-andls", destination: "/al-andalus-hospital" },
  { source: "/moufak-jewelry", destination: "/moufak-jewelry" },
  { source: "/mshfa-mzlwmyan", destination: "/mazlomyan-hospital" },
  { source: "/fndq-al-mdynh", destination: "/al-madina-hotel" },
  { source: "/mshfa-al-braam", destination: "/al-baram-hospital" },
  {
    source: "/mshfa-jrmana-al-jrahy",
    destination: "/jaramana-surgical-hospital",
  },
  {
    source: "/thanwyh-dmshq-al-arbyh",
    destination: "/highschool-dmshq-al-arbyh",
  },
  { source: "/mjwhrat-mash", destination: "/jewelry-mash" },
  { source: "/fndq-al-slam", destination: "/al-salam-hotel" },
  {
    source: "/mdrsh-al-dar-al-talymyh-al-khash",
    destination: "/aldar-altaalimia-private-school",
  },
  { source: "/mstshfa-al-nwr", destination: "/al-nour-hospital" },
  {
    source: "/mossh-alya-al-talymyh-al-khash-alia-school",
    destination: "/mossh-alya-al-talymyh-al-khash-alia-school",
  },
  { source: "/mswghat-mshlh", destination: "/mswghat-mshlh" },
  { source: "/mjwhrat-adnan", destination: "/jewelry-adnan" },
  { source: "/mdrsh-al-hkmh", destination: "/al-hikmah-school" },
  {
    source: "/mjwhrat-ghadh-gada-jewelry",
    destination: "/jewelry-ghadh-gada-jewelry",
  },
  {
    source: "/country/jo/category/technology-companies",
    destination: "/country/jo/category/technology-companies",
  },
  {
    source: "/mjwhrat-abnaa-mamwn-al-rfaay",
    destination: "/jewelry-abnaa-mamwn-al-rfaay",
  },
  { source: "/mjwhrat-qfaf", destination: "/jewelry-qfaf" },
  { source: "/fndq-al-jlaa", destination: "/al-jalaa-hotel" },
  { source: "/mshfa-al-tb-al-hdyth", destination: "/modern-medicine-hospital" },
  { source: "/fndq-harwn", destination: "/haroun-hotel" },
  { source: "/fndq-al-sham", destination: "/al-sham-hotel" },
  { source: "/mjwhrat-al-mlkh", destination: "/jewelry-al-mlkh" },
  {
    source: "/fndq-dmshq-al-dwly",
    destination: "/damascus-international-hotel",
  },
  { source: "/fndq-shyratwn-hlb", destination: "/sheraton-aleppo-hotel" },
  { source: "/fndq-afamya", destination: "/afamia-hotel" },
  { source: "/fndq-blw-tawr", destination: "/blue-tower-hotel" },
  {
    source: "/mjwhrat-sarh-sara-jewelery",
    destination: "/jewelry-sarh-sara-jewelery",
  },
  { source: "/ramsis", destination: "/ramsis" },
  {
    source: "/rwdh-al-tfwq-al-nmwdhjyh",
    destination: "/kindergarten-al-tfwq-al-nmwdhjyh",
  },
  { source: "/mstshfa-al-slam", destination: "/al-salam-hospital" },
  { source: "/mer-kuyumculuk", destination: "/mer-kuyumculuk" },
  { source: "/fndq-rwyal-smyramys", destination: "/royal-semiramis-hotel" },
  { source: "/fndq-al-rbya", destination: "/al-rabea-hotel" },
  { source: "/fndq-qsr-hlb", destination: "/qasr-aleppo-hotel" },
  {
    source: "/country/eg/category/financial-institutions",
    destination: "/country/eg/category/financial-institutions",
  },
  { source: "/mstshfa-frkwh", destination: "/farkuh-hospital" },
  { source: "/mjwhrat-al-ghmyan", destination: "/jewelry-al-ghmyan" },
  { source: "/mjwhrat-al-brhm", destination: "/jewelry-al-brhm" },
  { source: "/fndq-mdynh-al-yasmyn", destination: "/yasmin-city-hotel" },
  { source: "/fndq-al-zytwnh", destination: "/al-zaytouna-hotel" },
  {
    source: "/rwdh-amyh-al-khash",
    destination: "/kindergarten-amyh-al-khash",
  },
  { source: "/mjwhrat-kmwz-amany", destination: "/jewelry-kmwz-amany" },
  { source: "/fndq-fynysya", destination: "/vinisia-hotel" },
  { source: "/fndq-znwbya", destination: "/zenobia-hotel" },
  { source: "/mjwahrt-hnyfh-adwnys", destination: "/mjwahrt-hnyfh-adwnys" },
  { source: "/fndq-karltwn", destination: "/carlton-hotel" },
  { source: "/krystal-bal-as", destination: "/krystal-bal-as" },
  { source: "/mjwhrat-slyman-slamh", destination: "/jewelry-slyman-slamh" },
  { source: "/fndq-shhryar", destination: "/shahriar-hotel" },
  { source: "/saladin-hotelhostel", destination: "/saladin-hotelhostel" },
  {
    source: "/jewelryhanifa-mjwhrat-hyfh",
    destination: "/jewelryhanifa-mjwhrat-hyfh",
  },
  {
    source: "/country/eg/category/educational-centers",
    destination: "/country/eg/category/educational-centers",
  },
  { source: "/mqha-aal-bal", destination: "/mqha-aal-bal" },
  {
    source: "/country/lb/category/beauty-centers",
    destination: "/country/lb/category/beauty-centers",
  },
  {
    source: "/country/sy/category/technology-companies",
    destination: "/country/sy/category/technology-companies",
  },
  {
    source: "/country/eg/category/beauty-centers",
    destination: "/country/eg/category/beauty-centers",
  },
  {
    source: "/country/sy/category/technology",
    destination: "/country/sy/category/technology",
  },
  { source: "/dfh-w-lfh", destination: "/dfh-w-lfh" },
  { source: "/shawrma-al-shryf", destination: "/shawrma-al-shryf" },
  { source: "/hartna", destination: "/hartna" },
  { source: "/damaska-snaack", destination: "/damaska-snaack" },
  { source: "/mshfa-al-swfy", destination: "/al-soufi-hospital" },
  { source: "/mshfa-nwr-al-aabdyn", destination: "/noor-al-abedin-hospital" },
  { source: "/mshfa-alaj-al-srtan", destination: "/cancer-treatment-hospital" },
  { source: "/zryab-kafyh", destination: "/zryab-kafyh" },
  { source: "/mstshfa-draj", destination: "/daraj-hospital" },
  { source: "/mshfa-bhrw-al-nsaey", destination: "/bahro-gynecology-hospital" },
  { source: "/bytza-al-qymryh", destination: "/bytza-al-qymryh" },
  { source: "/mshfa-al-nda", destination: "/al-nada-hospital" },
  {
    source: "/country/lb/city/jaballubnan",
    destination: "/country/lb/city/jaballubnan",
  },
  {
    source: "/country/sy/category/commercial-shops/supermarket",
    destination: "/country/sy/category/commercial-shops/supermarket",
  },
  {
    source: "/country/sy/city/latakia/sub-area/almashrue-althaani",
    destination: "/country/sy/city/latakia/sub-area/almashrue-althaani",
  },
  {
    source: "/country/lb/city/beirut/sub-area/alhamra",
    destination: "/country/lb/city/beirut/sub-area/alhamra",
  },
  { source: "/search", destination: "/search" },
  { source: "/reviews", destination: "/reviews" },
  {
    source: "/country/sy/city/damascus/sub-area/souq-al-hamdeah",
    destination: "/country/sy/city/damascus/sub-area/souq-al-hamdeah",
  },
  {
    source: "/country/lb/city/beirut/sub-area/al'ashrafia",
    destination: "/country/lb/city/beirut/sub-area/al'ashrafia",
  },
  {
    source: "/country/lb/city/jaballubnan/sub-area/jwnia",
    destination: "/country/lb/city/jaballubnan/sub-area/jwnia",
  },
  {
    source: "/country/sy/city/damascus/sub-area/abo-rmana",
    destination: "/country/sy/city/damascus/sub-area/abo-rmana",
  },
  {
    source: "/country/sy/city/aleppo/sub-area/alshahba",
    destination: "/country/sy/city/aleppo/sub-area/alshahba",
  },
  {
    source: "/country/sy/city/damascus/sub-area/bab-sharqe",
    destination: "/country/sy/city/damascus/sub-area/bab-sharqe",
  },
  {
    source: "/country/sy/city/damascus/sub-area/qaseon",
    destination: "/country/sy/city/damascus/sub-area/qaseon",
  },
  {
    source: "/country/lb/category/financial-institutions",
    destination: "/country/lb/category/financial-institutions",
  },
  {
    source: "/country/eg/category/software-companies",
    destination: "/country/eg/category/software-companies",
  },
  {
    source: "/country/sy/city/latakia",
    destination: "/country/sy/city/latakia",
  },
  {
    source: "/country/eg/category/commercial-shops",
    destination: "/country/eg/category/commercial-shops",
  },
  {
    source: "/country/lb/category/software-companies",
    destination: "/country/lb/category/software-companies",
  },
  {
    source: "/country/lb/category/technology-companies",
    destination: "/country/lb/category/technology-companies",
  },
  { source: "/auth/forgot-password", destination: "/auth/forgot-password" },
];

module.exports = { legacyRedirects };
